# Generated by Django 5.2.15 on 2026-06-16 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prono', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_read_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
