# Generated by Django 5.2.15 on 2026-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prono', '0003_membership_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
